apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
spec:
  replicas: {{ .Values.loadGenerator.replicas }}
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
        - name: load-generator
          image: "{{ .Values.loadGenerator.image.repository }}:{{ .Values.loadGenerator.image.tag }}"
          imagePullPolicy: {{ .Values.loadGenerator.image.pullPolicy }}
          env:
            - name: PARQTEL_URL
              value: "http://parqtel:9090"
            - name: LOAD_TEST_MODE
              value: "false"
