image:
  repository: registry.localhost:5050/parqtel
  tag: dev
  pullPolicy: Always

resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 64Mi

storage:
  enabled: false

parqtel:
  storage:
    retentionDays: 0 # Ephemeral
  ui:
    enabled: false

ingress:
  enabled: false
